import { Serwist } from "serwist";

// Precache all static assets generated by Next.js
// @serwist/next will populate the precache manifest during build
const serwist = new Serwist({
  precacheEntries: [],
  skipWaiting: true,
  clientsClaim: true,
});

// Cache images with CacheFirst strategy
// eslint-disable-next-line @typescript-eslint/no-explicit-any
self.addEventListener("fetch", (event: any) => {
  const url = new URL(event.request.url);

  // Cache images from Unsplash and R2
  if (
    url.hostname === "images.unsplash.com" ||
    url.hostname.endsWith(".r2.cloudflarestorage.com")
  ) {
    event.respondWith(
      caches.open("images").then((cache) =>
        cache.match(event.request).then((cached) => {
          if (cached) return cached;
          return fetch(event.request).then((response) => {
            if (response.ok) {
              cache.put(event.request, response.clone());
            }
            return response;
          });
        })
      )
    );
    return;
  }

  // Network-first for API calls
  if (url.pathname.startsWith("/api/")) {
    event.respondWith(
      fetch(event.request).catch(() =>
        new Response(JSON.stringify({ error: "Offline" }), {
          status: 503,
          headers: { "Content-Type": "application/json" },
        })
      )
    );
    return;
  }
});
